General:
    epochs: &epochs 100
    seed: 123456
    acc_steps: 1

Data:
    dataset_name: 'coxreg'
    
    train_df: ./workspace/splits/tcga
    val_df: null
    test_df: null

    feat_dir: "./workspace/data/TCGA/wsis"
    report_dir: "./workspace/data/TCGA/reports"

    label_key: "status"
    image_key: "filename" 

    batch_size: 32
    num_workers: 8
    wsi_batch: true

Model:
    name: "models.MMClassifier"
    params:
        image_mil_name: "models.CLAM_Batch"

        mil_params:
            hidden_feat: 128
            gate: true
            size_arg: 'small'
            dropout: true
            instance_eval: false
            subtyping: false
            k_sample: 16
        feat_dim: 1024
        num_classes: 1


Optimizer:
    optimizer:
        name: Adam
        params:
            lr: 0.001
            amsgrad: False
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epochs
            last_epoch: -1

Loss:
    name: "models.model_utils.CoxSurvLoss"
    params:
        reduction: 'mean'
